services:
  mock-snmp:
    build:
      context: ./mock-devices
    command: ["snmpsim-command-responder", "--data-dir=/app/snmp-data", "--agent-udpv4-endpoint=0.0.0.0:161"]
    profiles: ["dev"]

  mock-targets:
    build:
      context: ./mock-devices
    command: ["python", "fake_targets.py"]
    profiles: ["dev"]
